a,b = input().split()
add = int(a) + int(b)
sub = int(a) - int(b)
mul = int(a) * int(b)
x = int(a) // int(b)
div2 = int(a) % int(b)
div1 = float(a) / float(b)

print(add)
print(sub)
print(mul)
print(x)
print(div2)
print(format(div1,".2f"))